CREATE TABLESPACE INGE_02 
   DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\INGE01.DBF' SIZE 250M 
   ONLINE;
CREATE TEMPORARY TABLESPACE INGE_temp01
   TEMPFILE 'C:\oraclexe\app\oracle\oradata\XE\INGEtemp02.dbf' SIZE 250M 
   AUTOEXTEND ON ;
   
CREATE USER INGE3 IDENTIFIED BY root
       DEFAULT TABLESPACE INGE_02
       TEMPORARY TABLESPACE INGE_temp01;     
      
GRANT RESOURCE TO INGE3; 
GRANT CONNECT TO INGE3;
GRANT ALL PRIVILEGES TO INGE3;

CREATE TABLE "INGE"."USUARIO_INGE" (
"CEDULA" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"NOMBRE" VARCHAR2(150 BYTE),
"CONTRASEÑA" VARCHAR2(12 BYTE),
"TIPO" VARCHAR2(20 BYTE), 
"EMAIL" VARCHAR2(60 BYTE),
"TELEFONO" VARCHAR(10 BYTE), 
CONSTRAINT "USUARIO_INGE_PK" PRIMARY KEY ("CEDULA"));

INSERT INTO USUARIO_INGE (CEDULA,NOMBRE,CONTRASEÑA,TIPO,EMAIL,TELEFONO)VALUES ('20764013','ALICIA HERNANDEZ','1234','ADMINISTRADOR','ali.34@gmail.com','3455424');

CREATE TABLE "INGE"."ESTADO" ( 
"CODIGO_ESTADO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"DETALLE" VARCHAR2(50 BYTE), 
CONSTRAINT "ESTADO_PK" PRIMARY KEY ("CODIGO_ESTADO"));

INSERT INTO ESTADO(CODIGO_ESTADO,DETALLE) VALUES ('000','NINGUNO');
INSERT INTO ESTADO(CODIGO_ESTADO,DETALLE) VALUES ('001','PRESELECCIONADO');
INSERT INTO ESTADO(CODIGO_ESTADO,DETALLE) VALUES ('002','EVALUADO');
INSERT INTO ESTADO(CODIGO_ESTADO,DETALLE) VALUES ('003','ENTREVISTADO');
INSERT INTO ESTADO(CODIGO_ESTADO,DETALLE) VALUES ('004','SELECCIONADO');
INSERT INTO ESTADO(CODIGO_ESTADO,DETALLE) VALUES ('005','CONTRATADO');
INSERT INTO ESTADO(CODIGO_ESTADO,DETALLE) VALUES ('006','DESCARTADO');
INSERT INTO ESTADO(CODIGO_ESTADO,DETALLE) VALUES ('006','FINALIZADO');




CREATE TABLE "INGE"."DEPARTAMENTO" (
"CODIGO_DEPARTAMENTO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"DESCRIPCION" VARCHAR2(50 BYTE), 
CONSTRAINT "DEPARTAMENTO_PK" PRIMARY KEY ("CODIGO_DEPARTAMENTO"));

INSERT INTO DEPARTAMENTO VALUES('001','NINGUNO');

CREATE TABLE "INGE"."REQUISICION" (
"NUMREQUISICION" NUMBER(*,0) NOT NULL ENABLE, 
"PUESTO" VARCHAR2(50 BYTE), 
"VACANTES" NUMBER(4,0), 
"CONTRATANTE" VARCHAR2(60 BYTE), 
"FECHA_INICIO" DATE, 
"FECHA_ENTREGA" DATE, 
"DEPARTAMENTO" VARCHAR2(20 BYTE),
"USUARIO" VARCHAR2(20 BYTE), 
"ESTADO" VARCHAR2(20 BYTE),
CONSTRAINT "REQUISICION_PK" PRIMARY KEY ("NUMREQUISICION"));

ALTER TABLE REQUISICION ADD CONSTRAINT FK_DEP FOREIGN KEY(DEPARTAMENTO)REFERENCES DEPARTAMENTO(CODIGO_DEPARTAMENTO);

ALTER TABLE REQUISICION ADD CONSTRAINT FK_USER FOREIGN KEY(USUARIO)REFERENCES USUARIO_INGE(CEDULA);

CREATE SEQUENCE  "INGE3"."AUTO_SEQ"
  MINVALUE 100 MAXVALUE 99999999999999
  INCREMENT BY 1 START WITH 732 NOCACHE
  ORDER  NOCYCLE ;

INSERT INTO REQUISICION (PUESTO,VACANTES,CONTRATANTE,FECHA_INICIO,FECHA_ENTREGA,DEPARTAMENTO, USUARIO)VALUES('NINGUNO',0,'NOMBRE',TO_DATE('12/01/2018', 'DD/MM/YYYY'),TO_DATE('13/01/2018', 'DD/MM/YYYY'),'001','20764013');

CREATE TABLE "INGE"."POSTULANTE" (
"CEDULA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"NOMBRE_COMPLETO" VARCHAR2(30 BYTE),
"EDAD" NUMBER(2,0),
"EXPERIENCIA" VARCHAR2(100 BYTE),
"LICENCIA" VARCHAR2(5 BYTE),
"ESPECIALIDAD" VARCHAR2(20 BYTE), 
"RESIDENCIA" VARCHAR2(20 BYTE), 
"ESTADO" VARCHAR2(4 BYTE), 
"REQUISICION" NUMBER, 
"TELEFONO" VARCHAR2(12 BYTE),
"NOTAS" VARCHAR2(200 BYTE),
"DOPRUEBA" CHAR(2 BYTE), 
CONSTRAINT "POSTULANTE_INGE_PK" PRIMARY KEY ("CEDULA"));

ALTER TABLE POSTULANTE ADD CONSTRAINT FK_REQ FOREIGN KEY(REQUISICION)REFERENCES REQUISICION(NUMREQUISICION);

ALTER TABLE POSTULANTE ADD CONSTRAINT FK_EST FOREIGN KEY(ESTADO)REFERENCES ESTADO(CODIGO_ESTADO);

INSERT INTO POSTULANTE (CEDULA, NOMBRE_COMPLETO, EDAD,EXPERIENCIA, LICENCIA, ESPECIALIDAD, TELEFONO,RESIDENCIA,ESTADO,REQUISICION)VALUES('207580624','LUIS ALEJANDRO CASTAING VARGAS',21,'NINGUNA','B1','INGENIERO','83113219','ALAJUELA','000',100);



CREATE TABLE "INGE.ENTREVISTADOS" (
"ID" NUMBER(*,0) NOT NULL ENABLE,
"POSTULANTE" VARCHAR2(20 BYTE),
"RESPUESTA" VARCHAR2(20 BYTE),
"TIPO" VARCHAR2(50 BYTE),
CONSTRAINT "ENTREVISTADO_INGE_PK" PRIMARY KEY ("ID"));

ALTER TABLE ENTREVISTADOS ADD CONSTRAINT FK_POS FOREIGN KEY(POSTULANTE) REFERENCES POSTULANTE(CEDULA);

CREATE SEQUENCE  "INGE3"."AUTO_SEQ_ENTREVISTADOS"
  MINVALUE 1 MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1 START WITH 389 CACHE 20
  NOORDER  NOCYCLE ;


CREATE TABLE "INGE.EVALUADOS" (
"CODIGO" NUMBER(*,0) NOT NULL ENABLE,
"POSTULANTE" VARCHAR2(20 BYTE),
"PRIORIDAD" NUMBER(4,0 BYTE),
CONSTRAINT "EVALUADO_INGE_PK" PRIMARY KEY ("CODIGO"));

ALTER TABLE EVALUADOS ADD CONSTRAINT FK_POS_EVA FOREIGN KEY(POSTULANTE) REFERENCES POSTULANTE(CEDULA);

CREATE SEQUENCE  "INGE3"."EVALUADOS_SEQ"
  MINVALUE 1 MAXVALUE 9999999999999999999999999999
  INCREMENT BY 1 START WITH 352 CACHE 20
  NOORDER  NOCYCLE ;


INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('102','VENTAS PROYECTOS');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('103','VENTAS ADHESIVOS');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('104','VENTAS CUENTAS CLAVE');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('105','VENTAS MERCADEO Y DISEÑO');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('201','PRODUCCIÓN SUPERVISORES');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('202','PRODUCCIÓN EMPAQUE');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('203','PRODUCCIÓN EMPAQUE');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('204','PRODUCCIÓN COCINADO');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('205','PRODUCCIÓN LABORATORIO');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('206','PRODUCCIÓN MANTENIMIENTO');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('207','PRODUCCIÓN LIMPIEZA Y MISCELANEOS');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('208','PRODUCCIÓN MONTACARGUISTAS');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('301','BODEGA OPERARIOS');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('302','BODEGA MONTACARGUISTAS');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('303','BODEGA CHOFER/AYUDANTE');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('304','BODEGA MISCELANEOS');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('401','ADMINISTRACIÓN RRHH');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('402','ADMINISTRACIÓN GENERAL');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('403','ADMINISTRACIÓN CONTABILIDAD');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('404','ADMINISTRACIÓN COBROS');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('405','ADMINISTRACIÓN FACTURACION');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('406','ADMINISTRACIÓN EXPORTACIONES');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('407','ADMINISTRACIÓN COMPRAS');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('408','ADMINISTRACIÓN FINANCIERA');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('409','ADMINISTRACIÓN MISCELANEOS');
INSERT INTO DEPARTAMENTO (CODIGO_DEPARTAMENTO,DESCRIPCION) VALUES ('410','ADMINISTRACIÓN RECEPCIÓN');

